### ISSUE TITLE
Call to undefined method Drupal\Core\Routing\LocalRedirectResponse::create()

### ISSUE THREAD

**Issue by ht1ppens** [jtyocum/drupal8-uwauth#15]
Line 455 of of UwAuthSubscriber.php is throwing the following error when I run this on Drupal 10.0.8:

`Error: Call to undefined method Drupal\Core\Routing\LocalRedirectResponse::create() in Drupal\uwauth\EventSubscriber\UwAuthSubscriber->redirectUser() (line 455 of /home/ht1ppens/documain/web/modules/contrib/uwauth/src/EventSubscriber/UwAuthSubscriber.php).`

Changing the line to: 

return new LocalRedirectResponse($current_uri);

fixes the error.

**Comment by tkiehne** [comment]
Resolved in 3.0.3
